apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: service
  name: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app.kubernetes.io/component: service
        app: python-app
    spec:
      containers:
        - name: python-app
          image: pythonapp-image:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000