apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: service
  name: python-app
spec:
  ports:
    - name: http
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: python-app
  type: NodePort